[Interface]
PrivateKey = YB25AU1TUV3nZF2rJ6mlKX6O6z/ETfc3p9IcX9xGlHg=
Address = 10.0.0.2/24

[Peer]
PublicKey = jqFCJoK5PUNejLYbxyl428lz5m+rlwEmV+C+2lePYTc=
Endpoint = 10.0.2.15:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
