[Interface]
PrivateKey = EDQJ9lFXWa/87rH52hhFs35Wcolwby5d0gH/74uXc1M=
Address = 10.0.0.1/24
ListenPort = 51820

[Peer]
PublicKey = uDcLUxRfA9QG+JHR561LKyJfjC30nykwqTE6w1Q0nkA=
AllowedIPs = 10.0.0.2/32
